ENV['VAGRANT_NO_PARALLEL'] = 'yes'

NODE_IP="192.168.60.10"

Vagrant.configure("2") do |config|


  config.vm.provider "virtualbox" do |v|
    v.memory = 1024 
    v.cpus = 1
  end

  config.vm.provider "libvirt" do |v|
    v.memory = 1024 
    v.cpus = 1
    v.nested = true
  end

  (1..3).each do |i|
    config.vm.provision "shell", inline: %Q{
      echo "#{NODE_IP}#{i}" "ubuntu#{i}" >> /etc/hosts
    }
  end
  (4..6).each do |i|
    config.vm.provision "shell", inline: %Q{
      echo "#{NODE_IP}#{i}" "centos#{i-3}" >> /etc/hosts
    }
  end

  # define 3 ubuntu machines
  (1..3).each do |i|
    config.vm.define "ubuntu#{i}" do |node|
      node.vm.box = "generic/ubuntu2004"
      node.vm.box_check_update = false
      node.vm.box_version = "3.4.0"
      node.vm.hostname = "ubuntu#{i}"
      node.vm.network "private_network", ip: "#{NODE_IP}#{i}"
      node.vm.provision "shell", path: "scripts/bootstrap.sh"
    end
  end

  # define 3 centos machines
  (4..6).each do |i|
    config.vm.define "centos#{i-3}" do |node|
      node.vm.box = "centos/7"
      node.vm.hostname = "centos#{i-3}"
      node.vm.network "private_network", ip: "#{NODE_IP}#{i}"
      node.vm.provision "shell", path: "scripts/bootstrap.sh"
    end
  end

  config.vm.define "node0" do |node|
    node.vm.box = "generic/ubuntu2004"
    node.vm.box_check_update = false
    node.vm.box_version = "3.5.2"
    node.vm.hostname = "node0"
    node.vm.network "private_network", ip: "#{NODE_IP}0"
    node.vm.provider "virtualbox" do |v|
      v.memory = 2048
      v.cpus = 1
    end

    node.vm.provision "shell", inline: %Q{
      resolvectl status
      apt-get -y update
      apt-get -y install software-properties-common
      apt-add-repository -y --update ppa:ansible/ansible
      apt-get -y install ansible
    }
    node.vm.provision "shell", privileged: false, path: "scripts/node0.sh"
  end
  
end
