Vagrant.configure("2") do |config|
  config.vm.box = "centos/7"
  config.vm.network :private_network, ip: "192.168.3.7"
  config.vm.provision :shell, path: "./install.sh"
  config.vm.network :forwarded_port, guest:9090, host:9090
end
