Vagrant.configure("2") do |config|
  config.vm.box = "ubuntu/xenial64"

  config.vm.provider "virtualbox" do |v|
    v.memory = 2048
    v.cpus = 2
  end

  config.vm.provision "shell", inline: %Q{
    echo "export PATH=$PATH:/opt/puppetlabs/bin:/opt/puppetlabs/puppet/bin" > /etc/profile.d/puppet-path.sh
  }

  3.downto(1).each do |i|
    config.vm.define "node#{i}" do |replica|
      replica.vm.hostname = "node#{i}"
      replica.vm.network "private_network", ip: "192.168.50.10#{i}"

      replica.vm.provision "shell", inline: %Q{
        apt-get -y update
        apt-get -y install wget
        wget http://apt.puppetlabs.com/puppet6-release-xenial.deb -O /tmp/puppet6-release-xenial.deb
        dpkg -i /tmp/puppet6-release-xenial.deb
        apt-get -y update
        apt-get -y install git vim tree puppetserver
        puppet module install puppet-mongodb --version 3.1.0
      }

      replica.vm.provision "puppet" do |puppet|
        puppet.manifests_path = "manifests"
        puppet.manifest_file = "replicaset.pp"
      end

    end
  end
  
end
