Vagrant.configure("2") do |config|
  config.vm.box = "centos/7"
  config.ssh.forward_agent = true
  config.ssh.insert_key = false

  config.vm.provision "shell", path: "scripts/hosts-file-setup.sh"
  config.vm.provision "shell", path: "scripts/install_packages.sh"
  config.vm.provision "shell", path: "scripts/configure_vim.sh"

  # configure mongo vms
  3.downto(1).each do |i|
    config.vm.define "mongodb#{i}" do |m|
      m.vm.hostname="mongodb#{i}"
      m.vm.network "private_network", ip: "10.50.3.#{i}0"
      m.vm.provision "shell", path: "scripts/mongodb.sh", args: "#{i}", run: "always"
    end
  end

  config.vm.provider "virtualbox" do |v|
    v.memory = 2048
    v.cpus = 2
  end
end
