Vagrant.configure("2") do |config|
  config.vm.box = "centos/7"

  vars = {
    "KAFKA_SUB_VERSION" => "2.6.0",
    "KAFKA_VERSION" => "kafka_2.12-$KAFKA_SUB_VERSION",
    "KAFKA_INSTALLATION_DIR" => "/opt",
    "KAFKA_HOME" => "$KAFKA_INSTALLATION_DIR/$KAFKA_VERSION"
  }

  as_str = vars.map{|k,str| ["export #{k}=#{str.gsub '$', '\$'}"]}.join("\n")

  config.vm.provision "shell", path: "scripts/hosts-file-setup.sh", env: vars
  config.vm.provision "shell", inline: "echo \"#{as_str}\">/etc/profile.d/kafka_vagrant_env.sh", run: "always"
  config.vm.provision "shell", path: "scripts/init.sh", env: vars

  # configure zookeeper cluster
  (1..3).each do |i|
    config.vm.define "zookeeper#{i}" do |z|
      z.vm.hostname = "zookeeper#{i}"
      z.vm.network "private_network", ip: "10.30.3.#{i+1}"
      z.vm.provision "shell", path: "scripts/zookeeper.sh", args: "#{i}", env: vars, run: "always"
    end
  end

  # configure brokers
  (1..3).each do |i|
    config.vm.define "broker#{i}" do |b|
      b.vm.hostname = "broker#{i}"
      b.vm.network "private_network", ip: "10.30.3.#{i+1}0"
      b.vm.provision "shell", path: "scripts/broker.sh", args: "#{i}", env: vars, run: "always"
    end
  end

  config.vm.provider "virtualbox" do |v|
    v.customize ["modifyvm", :id, "--cpuexecutioncap", "50"]
  end

end
