Vagrant.configure("2") do |config|
  config.vm.box = "centos/7"

  config.vm.provision "shell", path: "scripts/setup.sh"
  config.vm.provision "shell", path: "scripts/init.sh", run: "always"

  config.vm.network "private_network", type: "dhcp"

  config.vm.provider "virtualbox" do |vb|
    vb.memory=2048
    vb.cpus=2
  end

end
